# CIS 443 Exam 2, Part 2 Notebook
## 35 pts.
## Directions
1. Add your Grading ID below.
1. Answer each question in the cells provided.
1. When finished, save your work, close the Jupyter Lab file, and Shut Down Jupyter Lab. You will upload this Jupyter Notebook file as your submission to Question 1 in Exam 2, Part 2 in Blackboard.
1. Be sure to keep an unaltered version of this file just in case anything goes wrong in Blackboard.

__Grading ID__: ADD HERE (double click the cell in Jupyter to edit)

### Problem 1
Write a Python code fragment in the code cell below that reads a line of text, tokenizes the line using space characters as delimiters and outputs only those words beginning with the letter 't'. Ignore the case of the words. (__5 pts.__)

In [42]:
s = input("Enter your text: ")
s = s.lower()
for i in s.split(' '):
    if i.startswith('t'):
        print(i)


Enter your text: time to Test it out
time
to
test


### Problem 2
Write a Python code fragment in the code cell below that uses a _list comprehension_ to map the range of integers from 1 through 10 (inclusive) onto each value's triple (that is the value times 3) but filtered to only operate on the even numbers in the range (producing the triple of 2, the triple of 4, etc.). (__5 pts.__)

In [9]:
list = [val * 3 for val in range(1,11) if val %2 == 0]
print (list)

[6, 12, 18, 24, 30]


### Problem 3
Write a Python code fragment in the code cell below that defines a function named `unique_words` that receives a list of words, then determines and displays in alphabetical order only the unique words. Treat uppercase and lowercase letters the same. The function should use a __set__ to get the unique words in the list. Test your function with several sentences. (__7 pts.__)

In [40]:
def unique_words(list):
    list = list.lower()
    list1 = [i for i in set(list.split(' '))]
    print (sorted(list1))
    
unique_words(list = input("Enter sentence: ") )
        

Enter sentence: Ace This Test or get a Bee
['a', 'ace', 'bee', 'get', 'or', 'test', 'this']


### Problem 4
Write a Python code fragment in the code cell below that defines a function named `calc_qual_pts` that accepts a letter grade (a string) as a parameter and returns the GPA quality points, as specified below, <u>using a dictionary to map each letter grade to its associated quality points</u>. If the grade is not one of the standard letter grades (A, B, C, D, F), return -1 to indicate this. Test the function with grades of "A", "C", and "X". (__7 pts.__)

| Grade | Quality Points |
| ----- | -------------- |
| A     | 4.0            |
| B     | 3.0            |
| C     | 2.0            |
| D     | 1.0            |
| F     | 0.0            |
| Otherwise | -1         |

In [63]:
def calc_qual_pts(grades):
    grades = grades.upper()
    grade ={'A': '4.0', 'B': '3.0', 'C': '2.0', 'D': '1.0', 'F': '0.0'}
    final = grades in grade
    if final == True:
        print(grade[grades]) 
    else:
        print(grade.get('grades', -1))
calc_qual_pts(grades = input("Enter a string: ex. A "))


Enter a string: ex. A C
2.0


### Problem 5
Write a Python code fragment in the code cell below that implements a function named `merge_to_dict` that will accept two parallel lists as parameters, the `key_list` and the `value_list`, and will return a dictionary of the associated key-value pairs. Write your own loop to accomplish this (don't just call `zip`!). You may assume that the lists are the same length. Test with a list of 3 names as keys and a list of 3 scores as the values. (__5 pts.__)

In [107]:
def merge_to_dict(key_list, value_list):
    new = {}
    new = [ (key_list[i], value_list[i]) for i in range(0, len(key_list))]          
    print(new)
    
key_list = []
key_list = [i for i in input("Enter names: ").split()]
value_list = [int(i) for i in input("Enter test scores: ").split()]
merge_to_dict(key_list, value_list)

Enter names: tom som won tan
Enter test scores: 80 70 60 50
[('tom', 80), ('som', 70), ('won', 60), ('tan', 50)]


### Problem 6
Use _arange_ to create a 2-by-2 _ndarray_ containing the numbers 0–3. Use broadcasting to perform each of the following operations on the original array creating a new _ndarray_ and printing its contents: (__2 pts. each__)
1. Cube every element of the array.
1. Add 7 to every element of the array.
1. Multiply every element of the array by 2.

In [131]:
import numpy as np
num = np.arange(0,4).reshape(2,2)
print(f'num\n',(num))
num2 = num**3
print(f'num2\n',(num2))
num3 = num+7
print(f'num3\n',(num3))
num4 = num*2
print(f'num4\n',(num4))

num
 [[0 1]
 [2 3]]
num2
 [[ 0  1]
 [ 8 27]]
num3
 [[ 7  8]
 [ 9 10]]
num4
 [[0 2]
 [4 6]]
